  ; commands
  DRAW_PIXEL = $00
  GO_TEXT = $01
  GO_TILE = $02
  GO_BITMAP = $03
  CLEAR = $04
  DRAW_TRI = $05
  ;res0
  ;res1
  BACKSPACE = $08
  ;res2
  ;LF
  ;res3
  ;res4
  ;CR
  GO_LORES = $0e
  GO_HIRES = $0f
  SET_ADDR = $7e
  WRITE_RAW = $7f
  DRAW_PIX_SEQ = $80
  RESET = $ff

  ; colors
  BLACK = 0
  DK_GREEN = 1
  GREEN = 2
  LT_GREEN = 3
  DK_BLUE = 4
  BLUE = 5
  LT_BLUE = 6
  CYAN = 7
  RED = 8
  DK_ORANGE = 9
  ORANGE = 10
  YELLOW = 11
  MAGENTA = 12
  PINK = 13
  LT_PINK = 14
  WHITE = 15
